### ISSUE TITLE
Effect/Command Failed to Register

### ISSUE THREAD

**Issue by CoincidalRS** [theDanielJLewis/dynamic-compressor-for-audacity#2]
![image](https://user-images.githubusercontent.com/43393758/62421772-ffb76900-b65b-11e9-9686-887ad6772ce4.png)
I keep getting this error, I have tried with both the regular and advanced.ny file as well as the beta, running it from different folders and tried a few different things. Still can not get it to work and just keep getting this error.

**Comment by koesbong** [comment]
I had the same issue with Audacity 2.3.2 but it appears to work fine with 2.3.0

**Comment by jibberish666** [comment]
I get the same issue on 2.3.2

**Comment by theDanielJLewis** [comment]
Did you try the non-beta version?

**Comment by jibberish666** [comment]
Hi Daniel

Thanks for the update.  I just tried non-beta 1.2.6 and I can't register that in Audacity either.

Cheers

Phil

**Comment by jason-barba** [comment]
I enable the compressor, but it doesn't show up in the Effetcs list. No error message. Audacity v 2.1.2 on Windows 10.

**Comment by swinster** [comment]
just tried in Audacity 2.3.3, same issue. I guess there was change in audacity some time back that has broken this.

**Comment by theDanielJLewis** [comment]
Please follow the [official Audacity instructions for installing plugins](https://www.audacityteam.org/download/plug-ins/).

**Comment by swinster** [comment]
@theDanielJLewis unfortunately, there is nothing in that guide beyond what I think we are all doing. Other plugins seem to worth well. Perhaps we are all missing something obvious?

**Comment by swinster** [comment]
Ah, stupidity might be the answer I am looking for and I expect that others have done the same. They have probably saved the link referencing the git page the of the plugin, which actually saves an HTML document 🤦‍♂. Modify that with the actual contents of the `compress.ny` file made a bit of a difference 😉
