### ISSUE TITLE
"ill-formed Nyquist plug-in header" error message when trying to enable effect

### ISSUE THREAD

**Issue by sing8** [theDanielJLewis/dynamic-compressor-for-audacity#3]
I saved the compress.ny file by "control-click" save as, and put it into applications support/audacity/plug-ins folder and when I tried to enable it in audacity effects I got this error message. "ill-formed Nyquist plug-in header. did I do something wrong?

![Screen Shot 2020-05-07 at 19 05 14](https://user-images.githubusercontent.com/64968027/81300940-044ef900-9096-11ea-9d0f-1698095bf153.png)

**Comment by theDanielJLewis** [comment]
That "save as" method saves a webpage instead of the plugin. So you need to click the download button on the main page, open the zip file, and then move _that_ compress.ny file to your Audacity plug-ins folder.
